#!/bin/bash

# Include Detective v0.4 - by Unspongeful (https://metricpanda.com)
# Public Domain

# Version history
# v0.4 - Add option to set C++ mode using MODE env variable
# v0.3 - Add option to print includes
# v0.2 - Use CFLAGS environment variable to pass parameters to compiler
# v0.1 - Initial release

# Tested with GCC and Clang.

set -eou pipefail

printhelp()
{
  echo "Usage: $(basename "$0") [options] <file>"
  echo "Print include statistics about a C/C++ file or system header"
  echo ""
  echo "Options:"
  echo "   -p     print the preprocessed source instead of"
  echo "          computing stats"
  echo "   -d     print the preprocessor defines"
  echo "   -i     print nested includes"
  echo "   -h     show this help"
  echo "   -x     <file> is a C++ file"
  echo ""
  echo "Environment variables:"
  echo "   CC     path to the compiler executable"
  echo "   CFLAGS compilation flags to pass to the compiler."
  echo "          these flags cannot contain filenames or"
  echo "          output specifiers (e.g. -o)"
  echo "   MODE   specify MODE=c++ to process as C++"
}

# If CC env variable is not defined default to cc
if [ -z ${CC+x} ]; then
  CC=cc
fi

if [ -z ${CFLAGS+x} ]; then
  CFLAGS=
fi

# Table width
if [ -z ${WIDTH+x} ]; then
  WIDTH=70
fi

main()
{
  # If the source filename points to an existing file
  # include relative to working directory, otherwise
  # use system include
  if [ -f "$INPUT_FILE" ]; then
    c_string="\"$INPUT_FILE\""
    preprocessor_output=$($CC $COMPILER_ARGS -E $CFLAGS "$INPUT_FILE")
    defines_output=$($CC $COMPILER_ARGS -E $CFLAGS -dM "$INPUT_FILE")
  else
    c_string="<$INPUT_FILE>"
    preprocessor_output=$(echo "#include $c_string" | $CC $COMPILER_ARGS -E $CFLAGS -)
    defines_output=$(echo "#include $c_string" | $CC $COMPILER_ARGS -E $CFLAGS -dM -)
  fi
  nested_includes=$(echo "$preprocessor_output" | { grep -e '^# [0-9]* "[^<]' || true; })

  if [ $PRINT_SOURCE -eq 1 ]; then
    echo "$preprocessor_output" | sed '/^\s*$/d'
  fi
  if [ $PRINT_DEFINES -eq 1 ]; then
    echo "$defines_output"
  fi
  if [ $PRINT_INCLUDES -eq 1 ]; then
    echo "$nested_includes" | cut -d' ' -f 3 | sort | uniq
  fi
  exit_early=$(($PRINT_SOURCE+$PRINT_INCLUDES+$PRINT_DEFINES))
  if [ $exit_early -gt 0 ]; then
    exit 0
  fi

  # Lines of code
  total_lines=$(echo "$preprocessor_output" | wc -l)
  non_comment_lines=$(echo "$preprocessor_output" | sed '/^# /d' | wc -l)
  non_blank_lines=$(echo "$preprocessor_output" | sed '/^\s*$/d' | wc -l)
  blank_lines=$(($total_lines-$non_blank_lines))
  comment_lines=$(($total_lines-$non_comment_lines))
  code_lines=$(($non_comment_lines-$blank_lines))

  # Nested includes
  # https://gcc.gnu.org/onlinedocs/cpp/Preprocessor-Output.html
  total_includes=$(echo "$nested_includes" | cut -d' ' -f 3 | sort | uniq | wc -l)
  non_system_include=$(echo "$nested_includes" | sed '/".*3/d' | cut -d' ' -f 3 | sort | uniq | wc -l)
  system_include=$(($total_includes-non_system_include))

  # Preprocessor defines
  total_defines=$(echo "$defines_output" | wc -l)
  compiler_defines=$(echo "" | $CC $COMPILER_ARGS -E $CFLAGS -dM - | wc -l)
  include_defines=$(($total_defines-$compiler_defines))

  printheader "$c_string" "Lines of code" "Preprocessor defines" "Nested includes"

  printcell $code_lines "code"
  printcell $include_defines "from includes"
  printcell $non_system_include "user defined"
  endcolumn

  printcell $comment_lines "directives"
  printcell $compiler_defines "from compiler"
  printcell $system_include "system"
  endcolumn

  printfooter $non_blank_lines $total_defines $total_includes
}

printseparator()
{
  printf "%${SEPARATOR_WIDTH}s\n" | tr ' ' -
}

printheader()
{
  printf "%-9s $B${CC}$R ($MODE)\n" "Compiler:"
  printf "%-9s $B${CFLAGS}$R\n" "Flags:"
  printf "%-9s $B$1$R\n" "File:"
  printf "\n$B%-${COLUMN_WIDTH}s%-${COLUMN_WIDTH}s%-${COLUMN_WIDTH}s$R\n" "$2" "$3" "$4"
  printseparator
}

printcell()
{
  local color=""
  if [ $1 -eq 0 ]; then
    color=""
  fi
  printf "%-${TEXT_WIDTH}s$color%5d$R   " "$2" $1
}

endcolumn()
{
  printf "\n"
}

printfooter()
{
  printseparator
  printf "%-${TEXT_WIDTH}s$B%${FIRST_COLUMN_WIDTH}d%${COLUMN_WIDTH}d%${COLUMN_WIDTH}d$R\n" "Totals:" "$1" "$2" "$3"
}

# Pretty colors only in terminal
if [ -t 1 ];  then
  R="\033[0m" # Reset
  G="\033[37m" # Gray
  B="\033[1m" # Bold
else
  R=""
  G=""
  B=""
fi

COLUMN_WIDTH=$((WIDTH/3))
SEPARATOR_WIDTH=$((WIDTH-4))
TEXT_WIDTH=$((COLUMN_WIDTH-8))
FIRST_COLUMN_WIDTH=$((COLUMN_WIDTH-(TEXT_WIDTH+3)))

COMPILER_ARGS=""
PRINT_SOURCE=0
PRINT_DEFINES=0
PRINT_INCLUDES=0
while getopts "pdxhi" opt; do
  case $opt in
    i)
      PRINT_INCLUDES=1
      ;;
    p)
      PRINT_SOURCE=1
      ;;
    x)
      MODE="C++"
      COMPILER_ARGS="-xc++"
      ;;
    d)
      PRINT_DEFINES=1
      ;;
    h)
      printhelp
      exit 1
      ;;
    \?)
      echo "Invalid option: -$opt" >&2
      exit 1
      ;;
  esac
done

shift $((OPTIND-1))

case ${MODE:-} in
  c++|C++|CXX|cxx)
    COMPILER_ARGS="-xc++"
    MODE="C++"
    ;;
  *)
    MODE="C"
    ;;
esac

if [ $# -eq 0 ]; then
  printhelp
  exit 1
else
  INPUT_FILE="$1"
  main
fi
